### ISSUE TITLE
RuntimeError: deque mutated during iteration

### ISSUE THREAD

**Issue by chrisspen** [ros-visualization/rqt_robot_monitor#6] opened 2018-01-24 01:50 UTC
I somewhat frequently get the following exception, which crashes Rqt:

    Traceback (most recent call last):
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_robot_monitor/timeline_view.py", line 195, in _slot_redraw
        for i, m in enumerate(self._timeline):
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_robot_monitor/timeline.py", line 158, in __iter__
        for msg in self._queue:
    RuntimeError: deque mutated during iteration

Googling shows this seems to be a common bug with Python's deque. Despite the docs advertisement that it's "thread-safe", it's not. Iterating over it while another thread adds or removes from it will throw this error.

[This SO question](https://stackoverflow.com/questions/30107212/add-to-a-deque-being-iterated-in-python) explains how to fix it. Alternatively, you could try using a [Queue](https://docs.python.org/2/library/queue.html) instead, which has proper thread-safe support.

**Comment by arne48** [comment] 2018-01-24 05:34
@chrisspen thank you for reporting this issue and make PR.
I would like to evaluate the introduction of locking within timeline.py against possible other solutions.
Can you please provide a scenario to reproduce this error as I didn't experience this behavior yet.

**Comment by chrisspen** [comment] 2018-01-24 06:09
It's a threading problem, so it's nondeterministic. I'm not sure what exact event, if any, triggers it. Monitor just crashes, even when I have it minimized and am not actively viewing it. I've experienced this routinely using the monitor on an x86 laptop to view diagnostics from a ROS master running on a Raspberry Pi 3. I'm using my patch, and it hasn't re-occurred, not have I've experienced any noticeable side effects. 

What concerns do you have about locking? That's typically how you make code thread-safe.

**Comment by arne48** [comment] 2018-01-24 06:32
Obviously it is non-deterministic but a description of the circumstances under which this problem occurs would be helpful as I myself also use this plugin quite a lot exactly like you master(RPi3) -> Laptop(rqt) but I myself never experienced such a crash. So it might help to figure out (a) the trigger conditions (load, number of messages p. second) as well as (b) verify that its reproducible.
I see the tendency for such an error following your argument but I need to test it as well and therefor providing a test-case (even non-deterministic) as you mentioned frequent crashes would be helpful for that.

About the concerns. Adding locking yourself to timeline is one option another on is using Queue which implements locking itself as you yourself pointed out. So a really thread-safe alternative to deque exists already and it might be more transparent to use it instead of placing locks somewhere where it is not directly evident why they are there. This is more a question of design instead of functionality.

**Comment by arne48** [comment] 2018-01-24 07:08
How did you tested your patch? 
Because you are using Kinetic did you cloned the master branch of this repository and changed that one?
If so it would be interesting if the unchanged master also showed this problem.
This is because there was a patch merged for this apparent threading bug but yet only deployed to Lunar due to the lack of impact.

**Comment by chrisspen** [comment] 2018-01-24 17:31
I tested it by replacing the code in my kinetic install with my patched code, and then running monitor. My robot publishes hundreds of diagnostics messages a minute, so if your setup isn't publishing that many, that could explain why you haven't experienced this. I also wasn't experiencing this until I started publishing more messages.

I don't understand the inner workings of the monitor as well as you, but you should be able to reproduce the bug by creating a node that publishes thousands of diagnostic messages, which should increase the chance that `Timeline.callback()` is called, mutating `self._queue`, at the same time that Timeline view calls `Timeline.__iter__()`.

**Comment by chrisspen** [comment] 2018-01-24 17:33
You think I should try testing it with the unpatched master code, since that's newer than the packaged kinetic code?

**Comment by arne48** [comment] 2018-01-25 07:59
Yes, please try it unpatched on your setup as well. 
Because I am still running a test at the moment with the unpatched master branch at a diagnostic update rate of 500Hz but didn't had any crashes so far. This also highly increases the input lag of the GUI.

**Comment by alireza-hosseini** [comment] 2018-02-02 16:23
@arne48 I also confirm that **rqt_robot_monitor** is crashing with exactly the same error output.

**Comment by arne48** [comment] 2018-02-03 00:08
@chrisspen and @alireza-hosseini can you please test the master branch or 0.5.8 tag if this error persists.
I did test it and can confirm that the plugin is not crashing anymore on master and 0.5.8
But I would like to have a confirmation from someone who experienced that error under normal conditions.
After this I will deploy the newest version also to kinetic.

**Comment by chrisspen** [comment] 2018-02-03 13:38
What's the easiest way to install from master? Just checkout and then run `sudo python setup.py install`?

**Comment by arne48** [comment] 2018-02-03 15:44
@chrisspen actually you just need to checkout the master branch into your "src" directory of your catkin workspace. Packages there should overlay the packages installed from repository. And then you can just start rqt.
But I normally also make an additional "catkin_make" (shouldn't be needed for python) to make sure all changes in the workspace leading to compilation or generation are done and starting my rqt with the argument "--force-discover" to make sure it finds my plugin.

**Comment by dirk-thomas** [comment] 2018-02-05 16:50
> you just need to checkout the master branch into your "src" directory of your catkin workspace. Packages there should overlay the packages installed from repository. And then you can just start rqt.
But I normally also make an additional "catkin_make" (shouldn't be needed for python) to make sure all changes in the workspace leading to compilation or generation are done and starting my rqt with the argument "--force-discover" to make sure it finds my plugin.

Just cloning a repository with a Python package into the workspace doesn't make it available in the devel or install space. You always have to invoke the build tool (at least once).

**Comment by arne48** [comment] 2018-02-05 23:25
@dirk-thomas thank you for clarifying this. 
Indeed is the usage of catkin also needed for python packages (the first time) as it generates an "_init_.py" in $WORKSPACE/devel/lib/python2.7/dist-packages/$PACKAGENAME which extends the path by the source directory of the package and therefore allow their usage.
Sorry my fault.

**Comment by arne48** [comment] 2018-02-07 08:12
I released the newer version for Kinetic now.
@chrisspen Thanks for pointing out the occurrence of this problem.
@alireza-hosseini  Thanks for confirming it

**Closed by arne48** 2018-02-07 08:12 UTC
